// Code generated by Kitex v0.4.4. DO NOT EDIT.

package relationservice

import (
	"context"
	relation "github.com/aldlss/MiniTikTok-Relation/app/kitex_gen/pb/relation"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FollowAction(ctx context.Context, Req *relation.FollowActionRequest, callOptions ...callopt.Option) (r *relation.FollowActionResponse, err error)
	ListFollow(ctx context.Context, Req *relation.ListFollowRequest, callOptions ...callopt.Option) (r *relation.ListFollowResponse, err error)
	ListFans(ctx context.Context, Req *relation.ListFansRequest, callOptions ...callopt.Option) (r *relation.ListFansResponse, err error)
	ListFriends(ctx context.Context, Req *relation.ListFriendsRequest, callOptions ...callopt.Option) (r *relation.ListFriendsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRelationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRelationServiceClient struct {
	*kClient
}

func (p *kRelationServiceClient) FollowAction(ctx context.Context, Req *relation.FollowActionRequest, callOptions ...callopt.Option) (r *relation.FollowActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowAction(ctx, Req)
}

func (p *kRelationServiceClient) ListFollow(ctx context.Context, Req *relation.ListFollowRequest, callOptions ...callopt.Option) (r *relation.ListFollowResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFollow(ctx, Req)
}

func (p *kRelationServiceClient) ListFans(ctx context.Context, Req *relation.ListFansRequest, callOptions ...callopt.Option) (r *relation.ListFansResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFans(ctx, Req)
}

func (p *kRelationServiceClient) ListFriends(ctx context.Context, Req *relation.ListFriendsRequest, callOptions ...callopt.Option) (r *relation.ListFriendsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFriends(ctx, Req)
}
